services:
  # 1. The Source of Truth (Postgres + pgvector)
  postgres:
    image: pgvector/pgvector:pg17-trixie
    container_name: vexi_postgres
    ports: 
      - "5432:5432"
    environment:
      POSTGRES_USER: vexi
      POSTGRES_PASSWORD: password
      POSTGRES_DB: vexi_core
    volumes:
      # Persist data locally
      - vexi_data:/var/lib/postgresql/data
      # Run init scripts on first startup
      - ./infra/migrations:/docker-entrypoint-initdb.d

  # 2. The Message Bus (Redis)
  redis:
    image: redis:8-alpine
    container_name: vexi_redis
    ports: 
      - "6379:6379"

volumes:
  vexi_data: