[package]
name = "vexi-worker"
version = "0.1.0"
edition = "2024"

[dependencies]
anyhow = "1.0.100"
dotenv = "0.15.0"
pgvector = "0.4.1"
redis = "1.0.2"
rig-core = "0.28.0"
serde = "1.0.228"
serde_json = "1.0.149"
sqlx = "0.8.6"
text-splitter = "0.29.3"
tokio = "1.49.0"
uuid = "1.19.0"
